# Matrices

In this lecture, we will look at the following concepts:

- Matrix as a `NumPy` array
- Adding two matrices
- Element-wise multiplication of two matrices
- Scaling matrices
- Function of matrices (element-wise)
- Transpose of a matrix
- Product of two matrices
- Product of a matrix and a vector
- Shape of a matrix
- Matrix of zeros
- Matrix of ones
- Identity matrix

In [ ]:
import numpy as np

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. The main difference is that a matrix is a two dimensional array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In the code given above, the function `np.array` creates a `NumPy` array from a nested list.

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B
C

array([[ 6,  8],
       [10, 12]])

## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then, 

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P = 3 * M
P

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Element-wise multiplication of matrices

Consider two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

The element-wise product is given by $\textbf{A} \odot \textbf{B}$:

$$
\textbf{C} = \textbf{A} \odot \textbf{B} = \begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A * B
C

array([[ 5, 12],
       [21, 32]])

## Functions (element-wise) of matrices

Given a matrix, we sometimes would want to apply a function to every element of the matrix. For example, we may want to take the absolute value of all the elements. Let us say $f$ is this function, then:

$$
\textbf{A} = \begin{bmatrix}
-1 & 2\\
-3 & -4
\end{bmatrix}
$$

then:

$$
f(\textbf{A}) = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [ ]:
A = np.array([[-1, 2], [-3, -4]])
f_A = np.abs(A)   # np.abs returns the absolute value

f_A

array([[1, 2],
       [3, 4]])

Note that the function could be anything. For example, we might want to square each element of the matrix. If $\textbf{A}$ is a matrix, then $\textbf{B}$ could be defined element-wise as follows

$$
B_{ij} = A_{ij}^2
$$

In `NumPy` this becomes:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = A ** 2

B

array([[ 1,  4],
       [ 9, 16]])

## Transpose of a matrix

Given a matrix $\textbf{M}$:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

then, its transpose $\textbf{M}^{T}$ is:

$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = np.transpose(M)

M_t

array([[1, 4],
       [2, 5],
       [3, 6]])

Often, some methods in `NumPy` are also attributes of `NumPy` arrays. For example, this same operation of transposing a matrix can be done as follows:

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = M.T

M_t

array([[1, 4],
       [2, 5],
       [3, 6]])

You must be aware of both these ways of transposing a matrix.

## Product of two matrices

Given two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 7], [8, 9], [10, 11]])

C = A @ B
C

array([[ 52,  58],
       [124, 139]])

## Product of a matrix and a vector

This is very similar to the product of two matrices. Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \textbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{Ax}$ is given by:

$$
\mathbf{C} = \mathbf{A x} = \begin{bmatrix}
44\\
107\\
170
\end{bmatrix}
$$

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x

C

array([ 44, 107, 170])

## Shape of a matrix

The dimensions of a matrix can be determined using the `shape` attribute for `NumPy` arrays. For a matrix $\mathbf{A}$:

$$
\mathbf{M} =  
\begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8
\end{bmatrix}
$$

This is a $4 \times 2$ matrix. In `NumPy` this becomes:

In [ ]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
M.shape

(4, 2)

The shape of an array is always represented as a tuple. For example, the shape of the matrix given above is $(4, 2)$.

## Matrix of zeros

In many algorithms, we might have to initialize a matrix with zeros. For example, consider a $2 \times 4$ matrix:

$$
\mathbf{M} = \begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

In `NumPy` this can be done as follows:

In [ ]:
M = np.zeros((2, 4))
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Note that the shape of the matrix is $(2, 4)$. Consequently, the argument to the method `np.zeros` should be a tuple if you want to create a matrix of zeros. Specifying it as `np.zeros(2, 4)` will throw an error!

## Matrix of ones

Similar to a matrix of zeros, we can come up with a matrix of ones. 

$$
\mathbf{M} = \begin{bmatrix}
1 & 1\\
1 & 1\\
1 & 1
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
M = np.ones((3, 2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Again, note that `np.ones(3, 2)` will throw an error. The final point to note is this: `np.zeros` and `np.ones` can be used to create vectors or matrices. If the argument is a tuple having two values, these two methods will return matrices. If just an integer is passed as argument, the method will return vectors. If we wish to be consistent, we could pass a tuple of size 1 to create vectors:

$$
\mathbf{x} = \begin{bmatrix}
1\\
1\\
1\\
1
\end{bmatrix}
$$

In [ ]:
x = np.ones((5, ))
x

array([1., 1., 1., 1., 1.])

## Identity matrix

Often, we might have to deal with identity matrices. A $3 \times 3$ identity matrix is as follows:

$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])